name: caller

on:
  workflow_dispatch:
    

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
