#https://github.com/orgs/community/discussions/12029
name: diff

on:
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'Stack name'
        required: true
        default: 'warning'
        type: choice
        options:
        - dig-plat-dev 
        - dig-exp-tst 
        - dig-exp-stub 
        - dig-exp-sit 
        - dig-exp-perf 
        - dig-exp-stg 
        - dig-plat-prod 
        - dig-plat-dev-staging-activation-stack 
        - dig-exp-tst-staging-activation-stack 
        - dig-exp-stub-staging-activation-stack 
        - dig-exp-sit-staging-activation-stack 
        - dig-exp-perf-staging-activation-stack 
        - dig-exp-stg-staging-activation-stack 
        - dig-plat-dev-production-activation-stack 
        - dig-exp-tst-production-activation-stack 
        - dig-exp-stub-production-activation-stack 
        - dig-exp-sit-production-activation-stack 
        - dig-exp-perf-production-activation-stack 
        - dig-exp-stg-production-activation-stack 
        - prod-staging-activation-stack 
        - prod-production-activation-stack

jobs:
  lint_synth:
    name: Lint and Diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Diff
        #run: npx cdktf diff ${{ inputs.stack-name }}
        run: echo "choice is ${{ github.event.inputs.stack-name }}" / ${{ inputs.stack-name }}
