name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  lint_synth:
    name: Lint and Synth
    runs-on:
      - self-hosted
      - vm:m5.large
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx prettier --check .
      - name: Synth
        run: npx cdktf synth
